//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDAlquilerEntities : DbContext
    {
        public BDAlquilerEntities()
            : base("name=BDAlquilerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Alquiler> TB_Alquiler { get; set; }
        public virtual DbSet<TB_Automovil> TB_Automovil { get; set; }
        public virtual DbSet<TB_Cliente> TB_Cliente { get; set; }
        public virtual DbSet<TB_Marca> TB_Marca { get; set; }
    }
}
