//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Alquiler
    {
        public int cod_auto { get; set; }
        public int cod_cli { get; set; }
        public Nullable<System.DateTime> fec_ini_asig { get; set; }
        public Nullable<System.DateTime> fec_fin_asig { get; set; }
    
        public virtual TB_Automovil TB_Automovil { get; set; }
        public virtual TB_Cliente TB_Cliente { get; set; }
    }
}
